name: Playwright Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 & Cache Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Playwright Browsers & Dependencies
        run: |
          mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"
          mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"

      - name: Run Playwright Tests
        run: mvn verify

      - name: Archive trace files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: target/traces/*.zip

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin