name: Playwright Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: '17'
          java-distribution: 'temurin'
          maven-version: '3.9.9'

      - name: Install Playwright Browsers & Dependencies
        run: |
          mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps"
          mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"

      - name: Run Playwright Tests
        run: mvn verify

      - name: Archive trace files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: target/traces/*.zip

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin